### ISSUE TITLE
crash when remove tab, add tab, then remove tab

### ISSUE THREAD

**Issue by Jiatu-Liu** [akihito-takeuchi/qt-draggable-tab-widget#2]
(with some update. the title is not perfectly correct, sorry.)
hi akihito, this is a great app. but i found a quite annoying default:

i creat a new tab like this:
mydockwidget = QDockWidget(mywinlabel, mywindow)
mydraggable = DraggableTabWidget()
mydraggable.addTab(mytab, mytablabel)
mydockwidget.setWidget(mydraggable)

i remove it like this:
index = mydockwidget.mydraggable.indexOf(mytab)
mydockwidget.mydraggable.removeTab(index)
mywindow.removeDockWidget(mydockwidget)
del mydraggable
del mydockwidget

this works for the first time you add and then remove tabs in a QMainWindow object. **it is possible to drag a tab out**. but it will crash once you add tabs again. **it is not possible to drag out a tab without crashing the app**. it crashes with a RuntimeError: wrapped C/C++ object of type DraggableTabBar has been deleted, which points to line 125: bar_region = bar_inst.visibleRegion()

is this something you can easily fix in your code or is it my way of removing tabs causes this crash? anyway, could you illustrate how to properly delete a tab and a DraggableTabWidget? Thanks!

**Comment by akihito-takeuchi** [comment]
Hi Jiatu-Liu,

I updated the python code and I believe this will fix your problem. Please kindly let me know your result.

Thanks!

**Comment by keithCollins77093** [comment]
I had the same problem. I'll download and try the new version. Thanks, Keith--Sent from my Android phone with GMX Mail. Please excuse my brevity.On 11/30/22, 1:31 PM Akihito Takeuchi ***@***.***> wrote:

   
  Hi Jiatu-Liu, 
  I updated the python code and I believe this will fix your problem. Please kindly let me know your result. 
  Thanks!

**Comment by akihito-takeuchi** [comment]
This issue has been fixed.
